name: release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            name: linux-x64
            target: bun-linux-x64
            out: big-fat-lunch-linux-x64
          - os: ubuntu-latest
            name: linux-x64-musl
            target: bun-linux-x64-musl
            out: big-fat-lunch-linux-x64-musl
          - os: macos-latest
            name: macos-arm64
            target: bun-darwin-arm64
            out: big-fat-lunch-macos-arm64
          - os: macos-latest
            name: macos-x64
            target: bun-darwin-x64
            out: big-fat-lunch-macos-x64
          - os: windows-latest
            name: windows-x64
            target: bun-windows-x64
            out: big-fat-lunch-windows-x64.exe

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install deps (stable)
        run: npm install

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"

      - name: Build binary
        run: |
          mkdir -p dist
          bun build ./main.js --compile --target=${{ matrix.target }} --outfile=./dist/${{ matrix.out }}

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.out }}
          path: dist/${{ matrix.out }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist

      - run: ls -R dist

      - uses: softprops/action-gh-release@v2
        with:
          files: dist/**/*
